version: "3.7"

services:
  # Based on https://github.com/tsenart/vegeta
  vegeta:
    labels:
      sdk-measurements.sentry.io/main: "1"
    build:
      context: .
      dockerfile: ./vegeta.dockerfile
    deploy:
      resources:
        reservations:
          cpus: '0.5'

  django-enable-profiling:
    restart: unless-stopped
    build:
      context: .
      args:
        SENTRY_DSN: "$SENTRY_DSN"
        SENTRY_PORT_BACKEND: "8080"
        APP_ENABLE_PROFILING: "1"
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          cpus: '0.5'

  django-disable-profiling:
    restart: unless-stopped
    build:
      context: .
      args:
        SENTRY_DSN: "$SENTRY_DSN"
        SENTRY_PORT_BACKEND: "8090"
        APP_ENABLE_PROFILING: "0"
    ports:
      - "8090:8090"
    deploy:
      resources:
        reservations:
          cpus: '0.5'

  postgres:
    build:
      context: postgres
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
