version: "3.7"

services:
  vegeta:
    labels:
      main_image: "1"
    build:
      context: .
      dockerfile: ./vegeta.dockerfile
    deploy:
      resources:
        reservations:
          cpus: '0.5'

  django-enable-profiling:
    image: django_enable_profiling
    restart: unless-stopped
    build:
      context: .
      args:
        SENTRY_DSN_BACKEND: "$SENTRY_DSN"
        SENTRY_PORT_BACKEND: "8080"
        APP_ENABLE_PROFILING: "1"
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          cpus: '0.5'

  django-disable-profiling:
    image: django_disable_profiling
    restart: unless-stopped
    build:
      context: .
      args:
        SENTRY_DSN_BACKEND: "$SENTRY_DSN"
        SENTRY_PORT_BACKEND: "8090"
        APP_ENABLE_PROFILING: "0"
    ports:
      - "8090:8090"
    deploy:
      resources:
        reservations:
          cpus: '0.5'

  postgres:
    build:
      context: postgres
      dockerfile: postgres.dockerfile
