# Generated by Django 4.0.5 on 2022-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=200)),
                ('countries', models.CharField(max_length=200)),
                ('date_added', models.CharField(max_length=200)),
                ('release_year', models.SmallIntegerField()),
                ('rating', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
